# docker-compose.dev.yml
services:
  server:
    container_name: serverNode
    build: ./server
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src/
  mongodb:
    image: mongo
    volumes:
      - .data:/data/db
  client:
    container_name: clientReact
    build:
      context: ./client/reactapp
      dockerfile: Dockerfile
    volumes:
      - ./client/reactapp/src/:/app/src/
      - "/app/node_modules"
    ports:
      - 8080:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
